GET http://localhost:3000/lists

### <- séparateur entre les requêtes

POST http://localhost:3000/lists
Content-type: application/x-www-form-urlencoded

name=sample
&position=3

### exemple avec JSON

POST http://localhost:3000/lists
Content-type: application/json

{
    "name": "sample",
    "position": "2"
}